name: Build Radiator

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Scan dependencies
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ORG: netboxlabs
        run: |
          # Run dependency scanners
          python scripts/scan_dependencies/cross_repo_mentions.py
          python scripts/scan_dependencies/check_helm_chart_info.py
          python scripts/scan_dependencies/check_repo_releases.py
          python scripts/scan_dependencies/enterprise_plugins.py
          python scripts/scan_dependencies/scan_upstream_versions.py

      - name: Generate dashboards
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ORG: netboxlabs
        run: |
          python scripts/generate_dashboard.py



      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
